### ISSUE TITLE
Update requests file for getting the latest url request

### ISSUE THREAD

**Issue by singhvib** [singhvib/open-llm#1]
The url will be updated on a regular basis for the local hosted llm. Help needed to get the dynamic link upon restart.

**Comment by iVibudh** [comment]
use the request library to get the url from the public library


import requests
def git_model_url():
    url = 'https://raw.githubusercontent.com/singhvib/open-llm/main/path'
    response = requests.get(url)
    response.raise_for_status()
    return response.text
